name: Fetch Census Data and Save to SQLite

on:
  workflow_dispatch:  # Manual trigger; change as needed

jobs:
  fetch-and-save-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install pandas requests

      - name: Run data fetch and save to SQLite
        env:
          CENSUS_API_KEY: ${{ secrets.CENSUS_API_KEY }}
        run: |
          python Capstone/Scripts/acs_data_to_sqlite.py

      # Create the Database directory if it doesn't exist
      - name: Create Database Directory
        run: |
          mkdir -p Database

      # Move all .db files to the Database directory
      - name: Move all SQLite files to Capstone/Database
        run: |
          mv *.db Database/

      - name: Add and commit the .db files
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add Database/*.db
          git commit -m "Add SQLite databases to Database"
          
      - name: List files in the workspace
        run: ls -la Database

      - name: Pull latest changes from remote
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${PERSONAL_ACCESS_TOKEN}@github.com/brutus-the-homeschooler/Capstone.git
          git pull origin main

      - name: Push changes to the repository
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          git push origin main
