name: Fetch Census Data and Save to SQLite

on:
  workflow_dispatch:  # Manual trigger; change as needed

jobs:
  fetch-and-save-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install pandas requests

      # Create the Database directory if it doesn't exist and move the .db file
      - name: Move SQLite file to Capstone/Database
        run: |
          mkdir -p Capstone/Database  # Create the directory if it doesn't exist
          mv data_dictionary.db Capstone/Database/data_dictionary.db

      - name: Add and commit the .db file
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add Capstone/Database/data_dictionary.db
          git commit -m "Add SQLite database to Capstone/Database"
          
      - name: List files in the workspace
        run: ls -la Capstone/Database

      - name: Pull latest changes from remote
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${PERSONAL_ACCESS_TOKEN}@github.com/brutus-the-homeschooler/Capstone.git
          git pull origin main

      - name: Push changes to the repository
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          git push origin main
