name: Test Secret

on:
  workflow_dispatch:  # Allows you to manually trigger the workflow

jobs:
  test-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Echo token length
        run: echo ${#PERSONAL_ACCESS_TOKEN}
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
